name = "Creative Create Modpack"
author = "Akarys"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "736e7472151bb82abb3b6112215e75f0775a2eb1b94cbb105a3c65b31a03b25a"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"
