name = "Creative Create Modpack"
author = "Akarys"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a42118f108d9ad75e450b15d952d9bbca20b7a3fd29b9a3d5aa33fd27f052d12"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"
