name = "Creative Create Modpack"
author = "Akarys"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62d794375438a97717b0ac38225d7b7613d6c24f5a41dc09acabc972d0562c39"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"
