name = "Creative Create Modpack"
author = "Akarys"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2035d489a143b67223fda44f15d082ebb0a18b60723b5dfb88392c2a108b0ab8"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"
